### PR TITLE
added ipython, irsa, and mast yaml files

### PR DESCRIPTION
**Pull request by astronomeralex**
added entries for ipython, irsa, and mast following the directions from their respective websites.

### CODE REVIEW

**Comment by astronomeralex** [comment]
@astrofrog -- just want to check on this pull request and see if there are improvements I can make? I imagine it got lost over Christmas vacation and such.

**Comment by astrofrog** [comment]
@astronomeralex - this looks good, thanks! Could you also run the `parse_entries.py` script then also add the `registry.json` file to this PR? (it will also indicate whether there are any errors).

**Comment by astronomeralex** [comment]
@astrofrog i added the `database.json` file. That's the only one modified by the python script.

**Comment by astrofrog** [comment]
:+1: - thanks!

**Pull request merged**
