### PR TITLE
Create oanspm

### PR DESCRIPTION
**Pull request by mgricher**

### CODE REVIEW

**Comment by mgricher** [comment]
Could you please include this acknowledgement for the Observatorio Astronómico Nacional in the Sierra San Pedro Mártir?

**Comment by astrofrog** [comment]
Thanks!

**Comment by mgricher** [comment]
Good morning.

Thanks.  On the other hand, I don't see "OAN-SPM" in the list of 
facilities at 

http://astrofrog.github.io/acknowledgment-generator/ .

Is this normal?

```
        Sincerely,
        Michael.
```

**Comment by astrofrog** [comment]
@mgricher - yes, I need to re-run a parsing script, will do this now!

**Comment by astrofrog** [comment]
Should be there now (be sure to force-refresh!)

**Comment by mgricher** [comment]
Good morning,

Thanks.  Indeed, it's now there.

```
        Sincerely,
        Michael.
```

**Pull request merged**
