### PR TITLE
Add MLSO facility and K-Cor instrument

### PR DESCRIPTION
**Pull request by dwijn**

### CODE REVIEW

**Comment by hamogu** [comment]
Thank you for your contribution. 

The end result looks good, however, having five commits for this small a change is a bit much, in particular as the last commit just reverts what was done before. Do you know how to "squash" commits with "git rebase -i"? If so, please squash these commits to one. If not, let me know and I'll do that for you when I get to it in the next few days (you'll still get credit for that your combined commit).

**Comment by dwijn** [comment]
Thanks for the pointer. I thought there would be some way to do this, but I couldn't figure it out yesterday. I'm still learning how to use git and github, I'm a recovering SVN user. I'm not 100% sure I did this right, I appear to have done something I wasn't intending with a force-push.

Edit: yeah, this doesn't look right so far as I can tell. I think I made a couple of rookie mistakes. I'm tempted to close this pull request, and try again.

**Comment by hamogu** [comment]
Thanks for trying. I'll fix it up (carefully) and take a screenshot of what I did so you can see how I did it.

**Comment by hamogu** [comment]
I also screwed it up because I also don't do that often. Anyway, I'll just merge as is.

**Pull request merged**
