### PR TITLE
Refactor of the page & code

### PR DESCRIPTION
**Pull request by onekiloparsec**
Updated the generator with:
- More modern-looking style, easily-configurable, responsive with Twitter Bootstrap framework
- A cleaner separation of concerns (html, data, js, code etc...)
- A lot simpler javascript code, and better use of jQuery
- An updated page_entries python script to produce a more sensible json data file.
- The clear display and handling of acknowledgment dependencies 
- A small signature at the bottom

What do you think?

### CODE REVIEW

**Comment by onekiloparsec** [comment]
This PR fixes #51 .

**Comment by astrofrog** [comment]
Wow, this looks great, thank you so much for refactoring everything! One minor thing - the focus rectangle around the search box (at least in Safari) appears truncated on the right:

screen shot 2016-09-18 at 09 07 07

Is that easy to fix?

**Comment by onekiloparsec** [comment]
Strangely, it is not truncated in my Safari... I don't know what I could do then. I just changed a little thing because the search box was too large in small screens. But I don't know if that will improve your case. You may want to play a bit with the search input CSS properties in `style.css`.

**Comment by onekiloparsec** [comment]
Do you need something else before merging the PR? I've been unable to reproduce your problem, unfortunately. Let me know if I can improve a bit more.

**Comment by astrofrog** [comment]
@onekiloparsec - thanks for all this work, and sorry for the delay in merging! (was afk for the last few days).

**Comment by astrofrog** [comment]
@onekiloparsec - the search box looks fine now btw, thanks!

**Comment by onekiloparsec** [comment]
Thanks!

**Pull request merged**
