### PR TITLE
Add new entries: ds9, pyradex, spectralcube, pvextractor, wcsaxes

### PR DESCRIPTION
**Pull request by keflavich**
All in the title.  I'm citing all these, and A&A has asked me to put these all
into footnotes, but I'd rather dump them into an acknowledgements section or
something.

### CODE REVIEW

**Comment by astrofrog** [comment]
Thanks!

**Comment by astrofrog** [comment]
I'll re-generate the page later this evening

**Comment by keflavich** [comment]
what do you have to do to re-generate the page?  I'd like to do it on my fork too

**Comment by keflavich** [comment]
nevermind - I see.  I did .yml instead of .yaml; I'll fix that in another PR

**Pull request merged**
