### PR TITLE
Switch to GitHub Actions

### PR DESCRIPTION
**Pull request by astrofrog**
@hamogu - sorry for the delay, finally getting to this.

Once I've checked the main part of the CI works I'll add in the auto-publish bit and set the token appropriately.

### CODE REVIEW

**Comment by astrofrog** [comment]
I'm going to merge and will add the token later as I don't have access to it right now

**Comment by hamogu** [comment]
Great, thanks. Do you know what I need to do to get CI run on #81 for that? Just rebase on gh-pages?

**Comment by astrofrog** [comment]
Yes rebasing should be fine

**Comment by astrofrog** [comment]
But wait to merge until I've tested the auto updating of the database

**Comment by hamogu** [comment]
I'll rebase the other PR, as a check of the test infrastructure

**Comment by hamogu** [comment]
rebased, tests work. Maybe you can just merge whenever you think it's ready?

**Comment by astrofrog** [comment]
@hamogu - it looks like it worked!

**Pull request merged**
