### PR TITLE
Adding sources, text trimming and typeahead

### PR DESCRIPTION
**Pull request by slowe**
Here are a few sources that could be added. I wasn't used to the web interface so I initially made some file naming mistakes.

### CODE REVIEW

**Comment by astrofrog** [comment]
Nice, thanks! I like the implementation to avoid repeated code. By the way, if you want to test it with your entries, run `parse_entries.py` and it will update the json file. If you can, also add the modified json file to this PR and it will avoid me having to generate it manually after merging.

For the repeated text, another option is to simply require people to assume that the sentence would start with "This research made is of" and not include it in the yaml files. Another option is to require this kind of syntax:

```
[This research made use of] SIMBAD, a ...
```

That is, if this is the first sentence, what is in `[]` gets used, otherwise it doesn't. These are just ideas, but just wondering what would be best, since with the changes in this PR we are dependent on a specific wording anyway in the YAML files (which is already a huge improvement).

**Comment by slowe** [comment]
I get lots of errors when I try to run the python script. I don't really use python (I know, I know) so my config is probably years out of date. Sorry.

**Comment by slowe** [comment]
Ahh. The problem wasn't my python installation. It seems I didn't get the yaml format correct when I used the Github web-editor to make the files. I didn't realise they were white-space-sensitive. I've fixed the offending files and updated `database.json`.

**Comment by slowe** [comment]
@astrofrog Umm. I got a bit carried away. I have attempted to solve #12 by making a type ahead search box from scratch. It updates a list as you type. It auto selects the top item so you can press return to add it. You can also use the up/down cursor keys to move up/down the list of suggestions.

**Comment by astrofrog** [comment]
@slowe - wow, this is truly fantastic! Works great :smile: Thank you so much for contributing to this, and please do feel free to make any other changes in future!

**Pull request merged**
